// Code generated by Slice Machine. DO NOT EDIT.

import AntiHero from './AntiHero/index.svelte';
import TextImage from './TextImage/index.svelte';
import MarkDown from './MarkDown/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	anti_hero: AntiHero,
	card: TextImage,
	mark_down: MarkDown,
	rich_text: RichText
};
