// Code generated by Slice Machine. DO NOT EDIT.

import Card from './Card/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	card: Card,
	rich_text: RichText
};
