// Code generated by Slice Machine. DO NOT EDIT.

import AntiHero from './AntiHero/index.svelte';
import TextImage from './TextImage/index.svelte';
import Features from './Features/index.svelte';
import Hero from './Hero/index.svelte';
import MarkDown from './MarkDown/index.svelte';
import PageHeading from './PageHeading/index.svelte';
import RichText from './RichText/index.svelte';
import Testimonials from './Testimonials/index.svelte';

export const components = {
	anti_hero: AntiHero,
	card: TextImage,
	features: Features,
	hero: Hero,
	mark_down: MarkDown,
	page_heading: PageHeading,
	rich_text: RichText,
	testimonials: Testimonials
};
